#!/usr/bin/env bash

_help="script/update is used to update the project after a fresh pull.\n\
If you have not worked on the project for a while, running script/update after \
a pull will ensure that everything inside the project is up to date and ready \
to work."

[ -f "bootstrap" ] && bootstrap
